### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by tobyball43**
Added 1 new pet ^_^

### CODE REVIEW

**Comment by lynnaloo** [comment]
This needs some conflicts resolved with the latest in `master` and then you're gtg

**Comment by tobyball43** [comment]
How do I do this sorry I'm a noob with GitHub :P

**Comment by lynnaloo** [comment]
No problem! You need to look at the code that's in the README.md in `master` and make sure all of those changes and your changes are included in this PR. If you're a beginner, Github Desktop makes that much easier than command line.

**Comment by lynnaloo** [comment]
This looks good, but it just needs to be merged with the latest code.

**Pull request merged**
