### PR TITLE
Added Foxwing

### PR DESCRIPTION
**Pull request by wesleycsj**
Cute Foxwing added to Readme.

### CODE REVIEW

**Comment by lynnaloo** [comment]
This looks good, but I have been pulling in change by order of pull request so this just needs to be updated with the other changes to the README.md.

**Comment by wesleycsj** [comment]
What can i do exactly about it?

**Comment by lynnaloo** [comment]
I think the easiest way to do it is probably to download the Github app and that will allow you to fix all of the conflicts in that branch. You can also close this PR and open a new one with the change and I'll make it next in line.

**Comment by wesleycsj** [comment]
Ok, i'll try. Sorry by inconvenience, i'm novice with git.

**Pull request closed without merging**
