### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by saksham-s**
Instructions about running the app.

### CODE REVIEW

**Comment by saksham-s** [comment]
Can you please verify.It is my first commit.

**Comment by lynnaloo** [comment]
I'd like to see it formatted just a bit prettier with some Github markdown (there's a cheatsheet on the web). You can view source on this too:

## How to Run the App
- Install Node.js
- Run `npm i` to install dependencies
- Run `node index.js`

**Comment by lynnaloo** [comment]
Github interprets `.md` files as Github Markdown, not JavaScript, so it doesn't have to be in a comment. You just have to use Markdown syntax. A `*` is a bullet and  `` around a sentence is to signify literal code snippets.

**Comment by saksham-s** [comment]
I have edited as required.Please see and suggest any modifications.And thanks for being patient with me.

**Comment by lynnaloo** [comment]
Looks great @saksham15082! Congrats 🎉

**Comment by saksham-s** [comment]
Thanks.Is there any more work for hacktoberfest(or even otherwise) in python,c,java.I would be glad to work under you.

**Comment by lynnaloo** [comment]
resolves #12

**Comment by lynnaloo** [comment]
@saksham15082 I don't do Python, but I'll see what I have for c.

**Comment by saksham-s** [comment]
@lynnaloo What is resolves 12?

**Comment by lynnaloo** [comment]
#12 is the github issue that this PR is related to. `resolves` will make Github automatically close that issue when the PR is pulled in.

**Comment by saksham-s** [comment]
@lynnaloo do i have to be made an assignee to be reviewed on the hacktoberfest?

**Comment by lynnaloo** [comment]
No, you got credit already just by me adding the label. You can use this tool to see what you got credit for: https://hacktoberfestchecker.herokuapp.com/.

**Pull request merged**
